apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-flask-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path:
        backend:
          serviceName: my-test
          servicePort: 5000